### ISSUE TITLE
running simulation on D-Hydro simulations.ipynb

### ISSUE THREAD

**Issue by aemondd** [RBTV1/SWE-GNN-paper-repository-#2]
hey, 
i encountered errors while trying to run `run_simulations` function on **D-Hydro simulations.ipynb** notebook
are the following files created or pre-existing, if the latter could you provide these files please? :
```
    output_map = f'{model_folder}\\SWE_GNN_dataset_map.nc'
    grid_file = f'{model_folder}\\SWE_GNN_dataset_net.nc'
    breach_polygon_file = f'{model_folder}\\Boundary01.pli'
```
just to know the characteristics, dimensions, varnames...etc.
thank you very much.

**Comment by RBTV1** [comment]
Hi, sure! You can find the requested files in here: https://surfdrive.surf.nl/files/index.php/s/oBnLosn1m27vJKs
These might not be the same simulations used in the paper, but the format is the same.
You might still encounter an error if you don't have the DHYDRO (Delft3D-FM) license, but at least you can explore the netcdf files.
If you have any problem with the download let me know, otherwise you can close the issue.

**Comment by aemondd** [comment]
thank you
